apiVersion: apps/v1
kind: Deployment
metadata:
  name: naveen-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: naveen-springboot
  template:
    metadata:
      labels:
        app: naveen-springboot
    spec:
      containers:
        - name: springboot
          image: naveensmily79/naveen-gradle-own:naveen-gradle-own
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: naveen-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: naveen-springboot